name: cattle_pulse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.1 # latest version
    
  #Firebase Related Dependecies  
  firebase_core: ^4.2.1 #Connection with firebase
  cloud_firestore: ^6.1.0 #for firestore data
  firebase_auth: ^6.1.2 #For authentication

  # Common Flutter Packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^1.1.1
  provider: ^6.1.2
  lucide_icons: ^0.257.0
  shared_preferences: ^2.2.2
  package_info_plus: ^9.0.0
  image_picker: ^1.2.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translation/

  # âœ… Correct place for custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
